language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script:
  - yarn test

notifications:
  email:
    reciepients:
      - tubamar@hotmail.com
    on_success: always
    on_failure: always

deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 551ef315-c1a1-4702-9e76-e94f5c0f1af8
  app: scaldy-platzi-store-backend
  on:
    repo: Scaldy/platzi-store-backend
